[package]
name = "wgpu_raymarching"
authors = ["wesfly <https://github.com/wesfly>"]
edition = "2024"

[dependencies]
cfg-if = "1"
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.10"
log = "0.4"
wgpu = "24.0"
pollster = "0.3"
bytemuck = { version = "1.16", features = ["derive"] }

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# console_error_panic_hook = "0.1.6"
# console_log = "1.0"
# wgpu = { version = "24.0", features = ["webgl"] }
# wasm-bindgen = "0.2"
# wasm-bindgen-futures = "0.4"
# web-sys = { version = "0.3", features = ["Document", "Window", "Element"] }

[[bin]]
name = "wgpu_raymarching"
path = "src/main.rs"
